services:
  app:
    build: .
    ports:
      - "${PORT:-8080}:80"
      - "8443:8443"
    environment:
      # Replace these values with your actual App credentials
      - VITE_APP_ID=${VITE_APP_ID}
      - VITE_APP_FUNCTIONS_VERSION=${VITE_APP_FUNCTIONS_VERSION}
      - VITE_APP_BASE_URL=${VITE_APP_BASE_URL}
      - SSL_ENABLED=${SSL_ENABLED}
      - SSL_CERT_PATH=/app/certs/cert.pem
      - SSL_KEY_PATH=/app/certs/key.pem
    volumes:
      - ./certs:/app/certs
    restart: always
