services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      # Replace these values with your actual App credentials
      - VITE_APP_ID=${VITE_APP_ID}
      - VITE_APP_FUNCTIONS_VERSION=${VITE_APP_FUNCTIONS_VERSION}
      - VITE_APP_BASE_URL=${VITE_APP_BASE_URL}
    restart: always
